echo "Load zshrc"

#
# Environment
#
### General
export LANG=en_US.UTF-8
export TERM=xterm-256color
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

export TMUX_PLUGIN_MANAGER_PATH=$XDG_CONFIG_HOME/tmux/plugins

### Homebrew
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";

### Go
export GOPATH=$HOME/.go

### Path
path=(
    $HOME/.go/bin(N-/)
    $HOME/.cargo/bin(N-/)
    $HOMEBREW_PREFIX/{sbin,bin}(N-/)
    $HOME/.local/bin(N-/)
    /usr/local/{sbin,bin}(N-/)
    /usr/{sbin,bin}(N-/)
    /{sbin,bin}(N-/)
    $path
)
typeset -Ug PATH

#
# Plugin Manager
#
### Added by Zinit's installer
if [[ ! -f ${ZDOTDIR}/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "${ZDOTDIR}/.zinit" && command chmod g-rwX "${ZDOTDIRE}/.zinit"
    command git clone https://github.com/zdharma/zinit "${ZDOTDIR}/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "${ZDOTDIR}/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk

#
# Alias
#
alias e='emacsclient -nw -a ""'
alias ekil='emacsclient -e "(kill-emacs)"'
alias g='git'
alias mk='command mkdir -p'

zinit ice as"program" from"gh-r" mv"bat* -> bat" pick"bat/bat"
zinit light sharkdp/bat
alias cat='bat'

zinit ice as"program" from"gh-r" pick"*/exa"
zinit light ogham/exa
alias ls='exa '
alias ll='exa -lh'
alias la='exa -alh'

zinit ice from"gh-r" as"program" pick"*/ghq"
zinit light x-motemen/ghq
alias gg='ghq get'

#
# Keybind
#
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char

#
# Completion
#
autoload -Uz compinit && compinit

zinit ice wait lucid blockf
zinit light zsh-users/zsh-completions

zinit wait lucid blockf is-snippet as"completion" for \
    OMZP::docker/_docker \
    OMZP::docker-compose/_docker-compose \
    OMZP::rust/_rust \
    OMZP::cargo/_cargo \
    OMZP::rustup/_rustup

setopt magic_equal_subst
setopt menu_complete
setopt no_flow_control

zstyle ':completion:*' format '%B%F{blue}%d%f%b'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:default' menu select=2

#
# History
#
HISTFILE=$ZDOTDIR/.zsh-history
HISTSIZE=100000
SAVEHIST=1000000

setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt inc_append_history
setopt share_history

#
# Appearance
#
zinit ice from"gh-r" as"program"; zinit light starship/starship
eval "$(starship init zsh)"

### fish like
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting
zinit light zdharma/history-search-multi-word
