name: CI

on: push

jobs:
  provisioning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- apply --source .

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: private_zsh
